export interface AiVideoScriptTemplate {
  id: string;
  title: string;
  genre: string;
  setting: string;
  characters: string;
  motions: string;
  stageDirections: [string, string, string, string];
  lighting: string;
  filter: string;
  camera: string;
}

/** Eight-second, four-beat scripts derived from pawscripts.md plus new sets. */
export const AI_VIDEO_SCRIPTS: AiVideoScriptTemplate[] = [
  {
    id: "superhero-pup",
    title: "Cape-Flapping Superhero Pup",
    genre: "heroic comedy",
    setting: "A rooftop above a bright, stylized city at sunrise",
    characters: "One heroic dog wearing a small red cape; preserve the pet's exact face, markings, coat, and proportions",
    motions: "Ears lift, head turns toward the skyline, cape flaps, then the dog plants both front paws in a proud hero pose",
    stageDirections: ["0-2s: close on the pet as the ears lift and eyes focus", "2-4s: head turns toward the skyline while the cape catches wind", "4-6s: camera arcs low as the pet steps forward", "6-8s: hold a proud hero pose with one final cape flutter"],
    lighting: "Warm sunrise key light, cool city fill, crisp golden rim light on fur",
    filter: "Polished family-film color, rich reds and blues, subtle cinematic bloom",
    camera: "Low-angle 35mm push-in with one smooth hero arc; no cuts that change identity",
  },
  {
    id: "lofi-window-cat",
    title: "Lofi Rainy Window Cat",
    genre: "calm lofi",
    setting: "A cozy reading nook beside a rain-streaked window at night",
    characters: "One relaxed cat on a cushion; preserve face, coat pattern, eye color, and body shape",
    motions: "Slow blink, ear twitch, small head turn toward rain, tail tip curls once",
    stageDirections: ["0-2s: rain reflections drift across the cat's fur", "2-4s: cat slow-blinks and one ear turns toward a drop", "4-6s: gentle head turn toward the window", "6-8s: tail tip curls and the cat settles into stillness"],
    lighting: "Soft amber lamp key, cool blue rain fill, wet-window reflections",
    filter: "Lofi film grain, muted teal and amber, soft halation",
    camera: "Locked medium close-up with a very slow dolly inward",
  },
  {
    id: "midnight-treat-heist",
    title: "Midnight Treat Heist",
    genre: "playful caper",
    setting: "A moonlit kitchen with a treat jar on a low counter",
    characters: "One sneaky pet and a treat jar; preserve the pet's appearance exactly",
    motions: "Crouch, tiptoe, glance left and right, stretch toward the jar, freeze when a light flicks on",
    stageDirections: ["0-2s: pet peeks around the doorway", "2-4s: exaggerated quiet tiptoe toward the counter", "4-6s: paw reaches for the jar as the lid rattles", "6-8s: light turns on and the pet freezes with an innocent look"],
    lighting: "Cool moonlight shafts with a warm refrigerator glow",
    filter: "High-contrast caper look, gentle vignette, clean fur detail",
    camera: "Ground-level tracking shot, quick rack focus to the treat jar, comic final hold",
  },
  {
    id: "golden-park-sprint",
    title: "Golden Hour Park Sprint",
    genre: "uplifting sports portrait",
    setting: "An open park path through tall grass at golden hour",
    characters: "One joyful pet running freely; exact identity and markings must remain stable",
    motions: "Powerful sprint, ears and fur move naturally, head turns briefly toward camera, then a joyful leap",
    stageDirections: ["0-2s: pet launches into a sprint", "2-4s: side tracking shot shows natural gait and fur motion", "4-6s: pet glances toward camera while running", "6-8s: small joyful leap into a sunlit finish"],
    lighting: "Low golden sun, luminous rim light, soft natural shadows",
    filter: "Warm cinematic Kodak-inspired color, restrained lens flare",
    camera: "Low stabilized side-track, then a slight slow-motion push for the final leap",
  },
  {
    id: "wizard-kitten",
    title: "Magical Wizard Kitten",
    genre: "whimsical fantasy",
    setting: "A miniature candlelit library with floating spell pages",
    characters: "One kitten in a tiny wizard hat; preserve the kitten's face, fur, and eye color",
    motions: "Paw taps an open book, ears lift, glowing motes spiral upward, kitten turns its head in wonder",
    stageDirections: ["0-2s: kitten studies the open book", "2-4s: one paw taps the page and runes begin glowing", "4-6s: pages and motes rise in a gentle spiral", "6-8s: kitten looks up as one harmless spark becomes a tiny paw shape"],
    lighting: "Warm candle key, violet magical fill, soft gold edge light",
    filter: "Storybook fantasy, jewel tones, controlled bloom and fine grain",
    camera: "Slow tabletop orbit ending in a close-up on the kitten's reaction",
  },
  {
    id: "victorian-cat",
    title: "Victorian Portrait Cat",
    genre: "historical portrait comedy",
    setting: "A richly furnished 1890s portrait studio with velvet drapes and carved wood",
    characters: "One cat dressed as a dignified pre-1900 statesperson; identity and coat pattern unchanged",
    motions: "Chin lifts, head turns three-quarters, one paw settles on a tiny book, dignified slow blink",
    stageDirections: ["0-2s: reveal the formal portrait pose", "2-4s: cat lifts chin and turns toward key light", "4-6s: paw settles on the book as dust motes drift", "6-8s: dignified slow blink and subtle portrait flash"],
    lighting: "Large north-window key, warm candle practicals, painterly edge light",
    filter: "Pre-1900 oil-portrait palette with modern photoreal fur and restrained sepia",
    camera: "Slow formal push-in, symmetrical composition, no modern objects",
  },
  {
    id: "royal-court-dog",
    title: "Royal Court Dog",
    genre: "historical royal pageant",
    setting: "An ornate eighteenth-century palace gallery",
    characters: "One dog as a benevolent royal figure in a fitted brocade coat; preserve anatomy and identity",
    motions: "Head turns, ears lift beneath the costume, one measured step forward, tail gives one proud wag",
    stageDirections: ["0-2s: establish the palace and royal silhouette", "2-4s: dog turns toward camera", "4-6s: one stately step as the brocade catches light", "6-8s: proud tail wag and gentle bow"],
    lighting: "Chandelier warmth, soft window fill, gold rim on the coat and fur",
    filter: "Lush period-drama grade, clean skin and fur detail, subtle film grain",
    camera: "Centered dolly-in with a small parallax move past foreground candelabra",
  },
  {
    id: "memorial-sunrise",
    title: "Memorial Sunrise",
    genre: "tender remembrance",
    setting: "A quiet meadow at sunrise with soft wildflowers and a distant rainbow haze",
    characters: "One beloved pet, healthy and peaceful, with exact face, coat markings, and familiar expression",
    motions: "Ears lift, head turns toward a warm breeze, fur catches light, pet looks calmly into camera",
    stageDirections: ["0-2s: sunrise reveals the pet resting in flowers", "2-4s: ears lift as a breeze moves the fur", "4-6s: pet turns gently toward camera", "6-8s: hold a peaceful familiar expression as light blooms softly"],
    lighting: "Soft sunrise key, delicate backlight, natural pastel sky fill",
    filter: "Respectful cinematic warmth, soft highlight bloom, no fantasy wings or altered anatomy",
    camera: "Slow eye-level push-in with a steady final portrait hold",
  },
  {
    id: "moonlight-maestro",
    title: "Moonlight Maestro",
    genre: "elegant musical fantasy",
    setting: "A candlelit chamber music room beneath tall windows filled with blue moonlight",
    characters: "One pet composer beside an original miniature piano; preserve the pet's exact face, coat, eye color, and proportions",
    motions: "The pet raises one paw, turns toward the keys, taps a single note, then looks proudly toward camera as sheet music stirs",
    stageDirections: ["0-2s: moonlight reveals the pet seated beside the piano", "2-4s: one paw rises while the ears focus on the music", "4-6s: paw taps one key and sheet music lifts gently", "6-8s: pet turns to camera and holds a proud final portrait"],
    lighting: "Soft blue moon fill, warm candle key, and a narrow silver rim defining individual fur strands",
    filter: "Polished period-film color with midnight blue, warm ivory, restrained bloom, and fine grain",
    camera: "One slow 35mm semicircle from the music stand to an eye-level portrait; no cuts",
  },
  {
    id: "joans-banner",
    title: "Joan's Banner",
    genre: "hopeful historical adventure",
    setting: "A misty stone courtyard at dawn with an original unmarked banner moving in a light breeze",
    characters: "One brave pet in lightweight original ceremonial armor; preserve identity and keep the costume clear of the face and ears",
    motions: "The pet lifts its head, takes one steady step, watches the banner rise, then faces the morning light",
    stageDirections: ["0-2s: reveal the pet in dawn mist beside the lowered banner", "2-4s: ears lift and the pet takes one measured step", "4-6s: the unmarked banner rises smoothly behind the pet", "6-8s: camera settles as the pet faces the light in a steady pose"],
    lighting: "Cool dawn ambience, warm sunrise edge light, soft reflections across the original armor",
    filter: "Respectful period-adventure grade with natural stone, muted steel, and warm gold highlights",
    camera: "Low eye-level push forward with one gentle crane rise, ending motionless on the pet",
  },
  {
    id: "santas-workshop-surprise",
    title: "Santa's Workshop Surprise",
    genre: "warm holiday comedy",
    setting: "An original toy workshop filled with wooden gifts, paper stars, and softly falling snow beyond the windows",
    characters: "One cheerful pet in a simple red winter coat with no copied marks; preserve the pet's face, coat, and anatomy",
    motions: "The pet hears a bell, turns toward a small gift box, nudges it open, then reacts to a tiny burst of paper stars",
    stageDirections: ["0-2s: pet rests beside wrapped gifts as one bell rings", "2-4s: ears lift and head turns toward a moving box", "4-6s: pet nudges the lid open with one paw", "6-8s: paper stars rise and the pet gives one delighted head tilt"],
    lighting: "Warm fireplace key, soft workshop practicals, cool snowy window fill, and gentle fur rim light",
    filter: "Premium family-holiday color, rich red and pine accents, clean highlights, and restrained sparkle",
    camera: "Stable waist-high dolly from the gift stack to the pet's reaction with one soft focus pull",
  },
  {
    id: "cleopatras-golden-entrance",
    title: "Cleopatra's Golden Entrance",
    genre: "regal historical pageant",
    setting: "An original sunlit palace hall with carved columns, linen curtains, and a shallow reflecting pool",
    characters: "One regal pet wearing an original broad jeweled collar that leaves the face unobstructed; preserve exact identity",
    motions: "The pet steps through moving curtains, pauses beside the pool, turns toward camera, then settles into a calm royal pose",
    stageDirections: ["0-2s: linen curtains part to reveal the pet", "2-4s: pet takes two slow steps as the collar catches light", "4-6s: reflection appears as the pet turns toward camera", "6-8s: hold a still royal pose while curtains settle"],
    lighting: "Strong warm sun shafts, soft reflected pool fill, and controlled golden edge light on the coat",
    filter: "Luxurious gold, lapis, and linen palette with photoreal fur and restrained cinematic haze",
    camera: "Centered 50mm backward glide matching the pet's steps, finishing in a symmetrical locked portrait",
  },
  {
    id: "rock-star-encore",
    title: "Rock Star Encore",
    genre: "joyful concert finale",
    setting: "An original small arena stage with abstract paw-shaped lights, light haze, and no logos or readable signage",
    characters: "One charismatic pet beside a safely placed miniature microphone; preserve the pet's face, markings, anatomy, and proportions",
    motions: "The pet looks toward the crowd, taps one paw to the beat, turns into a colored light, then finishes with a proud head lift",
    stageDirections: ["0-2s: stage lights rise behind the pet's silhouette", "2-4s: pet turns toward the crowd and taps one paw", "4-6s: camera arcs as colored light crosses the fur", "6-8s: pet lifts its head for a still encore pose as lights fade"],
    lighting: "Magenta and cyan stage wash, warm face key, white rim light, and controlled haze without strobing",
    filter: "Clean concert-film contrast with saturated accents, detailed fur, and no flicker or rapid effects",
    camera: "One smooth stabilized 28mm arc ending in a medium close-up; no rapid cuts or shaky movement",
  },
];

export const DEFAULT_AI_VIDEO_SCRIPT = AI_VIDEO_SCRIPTS[0];
